- name: Ensure C:\Temp directory exists
  win_file:
    path: C:\Temp
    state: directory

- name: Create file in C:\Temp
  win_copy:
    content: "{{ domain_users[1].username }}:{{ domain_users[1].password }}"
    dest: "C:\\Temp\\creds.txt"
