---
- name: Download Google Chrome package
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
    mode: '0644'

- name: Install required dependencies
  apt:
    name: 
      - gdebi-core
    state: present
    update_cache: yes

- name: Install Google Chrome
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
    state: present

- name: Clean up downloaded package
  file:
    path: /tmp/google-chrome-stable_current_amd64.deb
    state: absent