---
- name: Install AD Domain Services
  ansible.windows.win_feature:
    name: AD-Domain-Services
    state: present
    include_management_tools: true

- name: Install AD Forest
  microsoft.ad.domain:
    dns_domain_name: "{{ domain_name }}"
    safe_mode_password: "{{ safe_mode_password }}"
    install_dns: yes
    domain_netbios_name: "{{ netbios_name }}"

- name: Restart server
  ansible.windows.win_reboot:
    msg: "Restarting server for AD installation"
    pre_reboot_delay: 15
    post_reboot_delay: 60

- name: Wait for Active Directory Web Services to be running
  ansible.windows.win_service_info:
    name: ADWS
  register: adws_service
  until: adws_service.exists and adws_service.services[0].state == "started"
  timeout: 600
  delay: 20

- name: Wait for 120 seconds after ADWS is running
  ansible.builtin.pause:
    seconds: 120
